export const metadata = {
  title: "Saguaro Pallets",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{margin: '0'}}>{children}</body>
    </html>
  );
}
